-- =====================================================
-- SPRINT 1: DDL - BASE DE DATOS ODS 2.0
-- =====================================================

-- =====================================================
-- TABLA 1: ODS_ORIGINAL
-- =====================================================
CREATE TABLE ods_original (
    id_ods_original NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_ods      NUMBER(3) NOT NULL UNIQUE,
    nombre          VARCHAR2(150) NOT NULL,
    descripcion     CLOB NOT NULL,
    fecha_registro  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT chk_numero_ods CHECK (numero_ods BETWEEN 1 AND 17)
);

COMMENT ON TABLE ods_original IS 'ODS oficiales de la Agenda 2030 de la ONU';
COMMENT ON COLUMN ods_original.numero_ods IS 'Número oficial del ODS (1-17)';

-- =====================================================
-- TABLA 2: ODS_2
-- =====================================================
CREATE TABLE ods_2 (
    id_ods2           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ods_original   NUMBER NOT NULL,
    nombre            VARCHAR2(200) NOT NULL,
    descripcion       CLOB NOT NULL,
    estado            VARCHAR2(20) DEFAULT 'BORRADOR',
    fecha_creacion    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_creador   VARCHAR2(100) DEFAULT 'sistema' NOT NULL,
    
    CONSTRAINT fk_ods2_original
        FOREIGN KEY (id_ods_original)
        REFERENCES ods_original(id_ods_original)
        ON DELETE CASCADE,
    
    CONSTRAINT chk_estado_ods2 
        CHECK (estado IN ('BORRADOR', 'REVISION', 'APROBADO'))
);

CREATE INDEX idx_estado ON ods_2(estado);
CREATE INDEX idx_fecha_creacion ON ods_2(fecha_creacion);

COMMENT ON TABLE ods_2 IS 'ODS reformulados (versión 2.0) más específicos y medibles';

-- =====================================================
-- TABLA 3: METRICA
-- =====================================================
CREATE TABLE metrica (
    id_metrica     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ods2        NUMBER NOT NULL,
    nombre         VARCHAR2(150) NOT NULL,
    unidad         VARCHAR2(50) NOT NULL,
    valor_objetivo NUMBER(12,2) NOT NULL,
    valor_actual   NUMBER(12,2) DEFAULT 0.00,
    fecha_objetivo DATE,
    
    CONSTRAINT fk_metrica_ods2
        FOREIGN KEY (id_ods2)
        REFERENCES ods_2(id_ods2)
        ON DELETE CASCADE,
    
    CONSTRAINT uq_metrica_ods2 UNIQUE (id_ods2, nombre),
    CONSTRAINT chk_valor_objetivo CHECK (valor_objetivo >= 0)
);

CREATE INDEX idx_metrica_ods2 ON metrica(id_ods2);
COMMENT ON COLUMN metrica.unidad IS 'ej: Porcentaje, Toneladas, Cantidad';

-- =====================================================
-- TABLA 4: EVIDENCIA
-- =====================================================
CREATE TABLE evidencia (
    id_evidencia      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ods2           NUMBER NOT NULL,
    descripcion       VARCHAR2(300) NOT NULL,
    fuente            VARCHAR2(250) NOT NULL,
    fiabilidad        NUMBER(1) NOT NULL,
    tipo_fuente       VARCHAR2(50) DEFAULT 'Estudio',
    fecha_publicacion DATE,
    url               VARCHAR2(500),
    
    CONSTRAINT fk_evidencia_ods2
        FOREIGN KEY (id_ods2)
        REFERENCES ods_2(id_ods2)
        ON DELETE CASCADE,
    
    CONSTRAINT chk_fiabilidad CHECK (fiabilidad BETWEEN 0 AND 5),
    CONSTRAINT chk_tipo_fuente CHECK (tipo_fuente IN ('Estudio', 'Informe oficial', 'Legislación', 'Paper académico', 'Datos estadísticos')),
    CONSTRAINT uq_evidencia_ods2 UNIQUE (id_ods2, descripcion)
);

CREATE INDEX idx_evid_ods2 ON evidencia(id_ods2);
CREATE INDEX idx_fiabilidad ON evidencia(fiabilidad);

-- =====================================================
-- TABLA 5: VIABILIDAD
-- =====================================================
CREATE TABLE viabilidad (
    id_viabilidad    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ods2          NUMBER NOT NULL UNIQUE,
    impacto          NUMBER(2) NOT NULL,
    coste            NUMBER(2) NOT NULL,
    tiempo           NUMBER(2) NOT NULL,
    riesgo           NUMBER(2) NOT NULL,
    puntuacion_final NUMBER(4,2),
    fecha_evaluacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    evaluador        VARCHAR2(100),
    observaciones    CLOB,
    
    CONSTRAINT fk_viabilidad_ods2
        FOREIGN KEY (id_ods2)
        REFERENCES ods_2(id_ods2)
        ON DELETE CASCADE,
    
    CONSTRAINT chk_criterios CHECK (
        impacto BETWEEN 0 AND 10 AND
        coste   BETWEEN 0 AND 10 AND
        tiempo  BETWEEN 0 AND 10 AND
        riesgo  BETWEEN 0 AND 10
    ),
    CONSTRAINT chk_puntuacion_final CHECK (puntuacion_final BETWEEN 0 AND 10)
);

CREATE INDEX idx_puntuacion ON viabilidad(puntuacion_final DESC);

-- =====================================================
-- TABLA 6: HISTORIAL_ESTADOS
-- =====================================================
CREATE TABLE historial_estados (
    id_historial    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ods2         NUMBER NOT NULL,
    estado_anterior VARCHAR2(20),
    estado_nuevo    VARCHAR2(20) NOT NULL,
    fecha_cambio    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario         VARCHAR2(100) NOT NULL,
    comentario      VARCHAR2(500),
    
    CONSTRAINT fk_historial_ods2
        FOREIGN KEY (id_ods2)
        REFERENCES ods_2(id_ods2)
        ON DELETE CASCADE,
    
    CONSTRAINT chk_est_ant CHECK (estado_anterior IN ('BORRADOR', 'REVISION', 'APROBADO')),
    CONSTRAINT chk_est_nue CHECK (estado_nuevo IN ('BORRADOR', 'REVISION', 'APROBADO'))
);

CREATE INDEX idx_historial_ods2 ON historial_estados(id_ods2);
CREATE INDEX idx_fecha_cambio ON historial_estados(fecha_cambio);
